// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/05       [395781]
Creator        : bjoshi
Date           : Wed Jul 24 13:52:00 2019
Host           : Linux cmsbuild24.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/b/bjoshi/Analysis/workdirtmvaanalysisJul_11_2019/Code/CommonUtils/tmva
Training events: 37236
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
var_vertexKFChi2              var_vertexKFChi2              var_vertexKFChi2              Variable vertexKFChi2         units                             'F'    [0.000170780578628,98.0028686523]
var_svpvTauAngle              var_svpvTauAngle              var_svpvTauAngle              Variable svpvTauAngle         units                             'F'    [5.68933501199e-05,1.45606076717]
var_flightLenSig              var_flightLenSig              var_flightLenSig              Variable flightLenSig         units                             'F'    [0.297363936901,40.3349914551]
var_sumMuTrkKinkChi2          var_sumMuTrkKinkChi2          var_sumMuTrkKinkChi2          Variable sumMuTrkKinkChi2     units                             'F'    [5.59860038757,1349.42895508]
var_segCompMuMin              var_segCompMuMin              var_segCompMuMin              Variable segCompMuMin         units                             'F'    [0,1]
var_MinMIPLikelihood          var_MinMIPLikelihood          var_MinMIPLikelihood          Variable MinMIPLikelihood     units                             'F'    [1.02196088392e-06,0.995764613152]
var_isoMax                    var_isoMax                    var_isoMax                    Variable isoMax               units                             'F'    [0,44.1369857788]
var_maxdca                    var_maxdca                    var_maxdca                    Variable maxdca               units                             'F'    [0.000102996826172,6.07498550415]
NSpec 1
var_tauMass                   var_tauMass                   var_tauMass                   Variable tauMass              units                             'F'    [0.672131001949,3.83080458641]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var_vertexKFChi2", "var_svpvTauAngle", "var_flightLenSig", "var_sumMuTrkKinkChi2", "var_segCompMuMin", "var_MinMIPLikelihood", "var_isoMax", "var_maxdca" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[14][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][14];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.314339403977432;
   fWeightMatrix0to1[1][0] = 5.37644448272036;
   fWeightMatrix0to1[2][0] = -0.107911736570747;
   fWeightMatrix0to1[3][0] = 0.224151465329288;
   fWeightMatrix0to1[4][0] = -1.90443321937345;
   fWeightMatrix0to1[5][0] = 0.760998381954224;
   fWeightMatrix0to1[6][0] = -0.982646523837929;
   fWeightMatrix0to1[7][0] = 0.985766117172666;
   fWeightMatrix0to1[8][0] = -5.10069431273144;
   fWeightMatrix0to1[9][0] = 0.519044343386378;
   fWeightMatrix0to1[10][0] = -1.01354584236052;
   fWeightMatrix0to1[11][0] = 0.951136916400577;
   fWeightMatrix0to1[12][0] = -4.03541194717955;
   fWeightMatrix0to1[0][1] = 0.0768867132976276;
   fWeightMatrix0to1[1][1] = 0.158363138240261;
   fWeightMatrix0to1[2][1] = 22.9714667145444;
   fWeightMatrix0to1[3][1] = 0.325481303164543;
   fWeightMatrix0to1[4][1] = 1.84191682302808;
   fWeightMatrix0to1[5][1] = -0.898275283488614;
   fWeightMatrix0to1[6][1] = 0.196586101937311;
   fWeightMatrix0to1[7][1] = -2.22726195986944;
   fWeightMatrix0to1[8][1] = -5.01510118604757;
   fWeightMatrix0to1[9][1] = 0.597355589976497;
   fWeightMatrix0to1[10][1] = -0.954086914520061;
   fWeightMatrix0to1[11][1] = -0.103863395606367;
   fWeightMatrix0to1[12][1] = -1.24867704943655;
   fWeightMatrix0to1[0][2] = 1.38827800687947;
   fWeightMatrix0to1[1][2] = -1.73273326487499;
   fWeightMatrix0to1[2][2] = 0.00881181257685249;
   fWeightMatrix0to1[3][2] = -0.00514215212414578;
   fWeightMatrix0to1[4][2] = 0.663440537943502;
   fWeightMatrix0to1[5][2] = 0.443846118960083;
   fWeightMatrix0to1[6][2] = -0.998196549330675;
   fWeightMatrix0to1[7][2] = 0.148177285987404;
   fWeightMatrix0to1[8][2] = 2.55257461866329;
   fWeightMatrix0to1[9][2] = 0.810659286344122;
   fWeightMatrix0to1[10][2] = -0.910397394142347;
   fWeightMatrix0to1[11][2] = 0.905000701254311;
   fWeightMatrix0to1[12][2] = 0.505887770112318;
   fWeightMatrix0to1[0][3] = 0.18852648154392;
   fWeightMatrix0to1[1][3] = -1.32462002144425;
   fWeightMatrix0to1[2][3] = -0.452420807505791;
   fWeightMatrix0to1[3][3] = 1.74488470957914;
   fWeightMatrix0to1[4][3] = 1.01623975764379;
   fWeightMatrix0to1[5][3] = 0.911047319353527;
   fWeightMatrix0to1[6][3] = -1.79422007864419;
   fWeightMatrix0to1[7][3] = 1.05044129449538;
   fWeightMatrix0to1[8][3] = 0.452977548928807;
   fWeightMatrix0to1[9][3] = 5.40842771630664;
   fWeightMatrix0to1[10][3] = 2.08120366265266;
   fWeightMatrix0to1[11][3] = 0.74524175723249;
   fWeightMatrix0to1[12][3] = 0.821123592255165;
   fWeightMatrix0to1[0][4] = -1.74198045649818;
   fWeightMatrix0to1[1][4] = 0.169619283473397;
   fWeightMatrix0to1[2][4] = -0.104392236785639;
   fWeightMatrix0to1[3][4] = 0.215331803815804;
   fWeightMatrix0to1[4][4] = -1.35218048378921;
   fWeightMatrix0to1[5][4] = -4.08045442822233;
   fWeightMatrix0to1[6][4] = 0.334141334839934;
   fWeightMatrix0to1[7][4] = 3.01863229991933;
   fWeightMatrix0to1[8][4] = -0.17056807881364;
   fWeightMatrix0to1[9][4] = 0.279675233444435;
   fWeightMatrix0to1[10][4] = -1.74919142557035;
   fWeightMatrix0to1[11][4] = 0.975368916516122;
   fWeightMatrix0to1[12][4] = 0.126623806533533;
   fWeightMatrix0to1[0][5] = -0.281767100197129;
   fWeightMatrix0to1[1][5] = -0.881510877695527;
   fWeightMatrix0to1[2][5] = -0.0114647320994981;
   fWeightMatrix0to1[3][5] = 1.63334918020032;
   fWeightMatrix0to1[4][5] = -0.690147293168057;
   fWeightMatrix0to1[5][5] = -1.57232182161151;
   fWeightMatrix0to1[6][5] = -1.36018313364603;
   fWeightMatrix0to1[7][5] = 0.775655708648117;
   fWeightMatrix0to1[8][5] = -0.276674167195423;
   fWeightMatrix0to1[9][5] = -0.244350111198627;
   fWeightMatrix0to1[10][5] = -0.800047345330861;
   fWeightMatrix0to1[11][5] = -2.25884106776182;
   fWeightMatrix0to1[12][5] = -0.0411437293397653;
   fWeightMatrix0to1[0][6] = 1.76385973781058;
   fWeightMatrix0to1[1][6] = 0.242212727747231;
   fWeightMatrix0to1[2][6] = 0.378280466685002;
   fWeightMatrix0to1[3][6] = 1.66804582632854;
   fWeightMatrix0to1[4][6] = 1.24192918075558;
   fWeightMatrix0to1[5][6] = 0.429326451001765;
   fWeightMatrix0to1[6][6] = -1.65025549318457;
   fWeightMatrix0to1[7][6] = -0.446696599903109;
   fWeightMatrix0to1[8][6] = 2.0374497991971;
   fWeightMatrix0to1[9][6] = 0.487892686467156;
   fWeightMatrix0to1[10][6] = -1.86416035374069;
   fWeightMatrix0to1[11][6] = -2.65986798557925;
   fWeightMatrix0to1[12][6] = -5.03547595888948;
   fWeightMatrix0to1[0][7] = 0.154892324881649;
   fWeightMatrix0to1[1][7] = 1.27956140625083;
   fWeightMatrix0to1[2][7] = -11.7023164405868;
   fWeightMatrix0to1[3][7] = -1.76475917503337;
   fWeightMatrix0to1[4][7] = 1.65269200437508;
   fWeightMatrix0to1[5][7] = -1.25738773750399;
   fWeightMatrix0to1[6][7] = -2.47653956925329;
   fWeightMatrix0to1[7][7] = -2.57363661863487;
   fWeightMatrix0to1[8][7] = 2.029555632463;
   fWeightMatrix0to1[9][7] = -4.17830647470386;
   fWeightMatrix0to1[10][7] = -1.54415292062256;
   fWeightMatrix0to1[11][7] = -0.101915446219376;
   fWeightMatrix0to1[12][7] = 3.965774939972;
   fWeightMatrix0to1[0][8] = -1.30890358914976;
   fWeightMatrix0to1[1][8] = 1.33341912604623;
   fWeightMatrix0to1[2][8] = 10.6751503438518;
   fWeightMatrix0to1[3][8] = 0.0122609931746543;
   fWeightMatrix0to1[4][8] = -0.0567155823190634;
   fWeightMatrix0to1[5][8] = 1.34524025181421;
   fWeightMatrix0to1[6][8] = -0.775950043328975;
   fWeightMatrix0to1[7][8] = -0.288213859500563;
   fWeightMatrix0to1[8][8] = -3.97441385466278;
   fWeightMatrix0to1[9][8] = 2.44701946439906;
   fWeightMatrix0to1[10][8] = -1.27096361627718;
   fWeightMatrix0to1[11][8] = 2.74214332409053;
   fWeightMatrix0to1[12][8] = -5.10057336068853;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.5972421039152;
   fWeightMatrix1to2[0][1] = 0.974169841015607;
   fWeightMatrix1to2[0][2] = -2.78970301607012;
   fWeightMatrix1to2[0][3] = -0.838901101218736;
   fWeightMatrix1to2[0][4] = -0.533979252661564;
   fWeightMatrix1to2[0][5] = -0.748097105743877;
   fWeightMatrix1to2[0][6] = 1.74659686980069;
   fWeightMatrix1to2[0][7] = 1.60675983086225;
   fWeightMatrix1to2[0][8] = 1.41404548716105;
   fWeightMatrix1to2[0][9] = -1.78499793644836;
   fWeightMatrix1to2[0][10] = -0.914471652339965;
   fWeightMatrix1to2[0][11] = -0.816508539244343;
   fWeightMatrix1to2[0][12] = 1.85515484089454;
   fWeightMatrix1to2[0][13] = 0.861290338639151;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.000170780578628;
   fMax_1[0][0] = 98.0028686523;
   fMin_1[1][0] = 0.0188555326313;
   fMax_1[1][0] = 93.4388046265;
   fMin_1[2][0] = 0.000170780578628;
   fMax_1[2][0] = 98.0028686523;
   fMin_1[0][1] = 5.68933501199e-05;
   fMax_1[0][1] = 1.02695572376;
   fMin_1[1][1] = 0.000263659138;
   fMax_1[1][1] = 1.45606076717;
   fMin_1[2][1] = 5.68933501199e-05;
   fMax_1[2][1] = 1.45606076717;
   fMin_1[0][2] = 0.297363936901;
   fMax_1[0][2] = 22.4689235687;
   fMin_1[1][2] = 0.570846676826;
   fMax_1[1][2] = 40.3349914551;
   fMin_1[2][2] = 0.297363936901;
   fMax_1[2][2] = 40.3349914551;
   fMin_1[0][3] = 5.59860038757;
   fMax_1[0][3] = 1141.87963867;
   fMin_1[1][3] = 6.3308172226;
   fMax_1[1][3] = 1349.42895508;
   fMin_1[2][3] = 5.59860038757;
   fMax_1[2][3] = 1349.42895508;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 1;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 1;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 1;
   fMin_1[0][5] = 1.02196088392e-06;
   fMax_1[0][5] = 0.995764613152;
   fMin_1[1][5] = 2.44330976784e-06;
   fMax_1[1][5] = 0.993460714817;
   fMin_1[2][5] = 1.02196088392e-06;
   fMax_1[2][5] = 0.995764613152;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 44.1369857788;
   fMin_1[1][6] = 0.0299532283098;
   fMax_1[1][6] = 38.8205451965;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 44.1369857788;
   fMin_1[0][7] = 0.000102996826172;
   fMax_1[0][7] = 6.07498550415;
   fMin_1[1][7] = 0.000548541545868;
   fMax_1[1][7] = 1.81010973454;
   fMin_1[2][7] = 0.000102996826172;
   fMax_1[2][7] = 6.07498550415;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
