// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/05       [395781]
Creator        : bjoshi
Date           : Wed Jul 24 14:12:27 2019
Host           : Linux cmsbuild24.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/b/bjoshi/Analysis/workdirtmvaanalysisJul_11_2019/Code/CommonUtils/tmva
Training events: 40067
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
var_vertexKFChi2              var_vertexKFChi2              var_vertexKFChi2              Variable vertexKFChi2         units                             'F'    [0.000170780578628,99.7633666992]
var_svpvTauAngle              var_svpvTauAngle              var_svpvTauAngle              Variable svpvTauAngle         units                             'F'    [5.68933501199e-05,2.91128897667]
var_flightLenSig              var_flightLenSig              var_flightLenSig              Variable flightLenSig         units                             'F'    [0.249220505357,22.4689235687]
var_sumMuTrkKinkChi2          var_sumMuTrkKinkChi2          var_sumMuTrkKinkChi2          Variable sumMuTrkKinkChi2     units                             'F'    [5.59860038757,1910.75646973]
var_segCompMuMin              var_segCompMuMin              var_segCompMuMin              Variable segCompMuMin         units                             'F'    [0,1]
var_MinMIPLikelihood          var_MinMIPLikelihood          var_MinMIPLikelihood          Variable MinMIPLikelihood     units                             'F'    [1.02196088392e-06,0.995764613152]
var_isoMax                    var_isoMax                    var_isoMax                    Variable isoMax               units                             'F'    [0,44.1369857788]
var_maxdca                    var_maxdca                    var_maxdca                    Variable maxdca               units                             'F'    [0.000102996826172,6.07498550415]
NSpec 1
var_tauMass                   var_tauMass                   var_tauMass                   Variable tauMass              units                             'F'    [0.672131001949,3.83080458641]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var_vertexKFChi2", "var_svpvTauAngle", "var_flightLenSig", "var_sumMuTrkKinkChi2", "var_segCompMuMin", "var_MinMIPLikelihood", "var_isoMax", "var_maxdca" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[14][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][14];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.556337441313496;
   fWeightMatrix0to1[1][0] = 5.68791001353927;
   fWeightMatrix0to1[2][0] = 1.56795393448042;
   fWeightMatrix0to1[3][0] = 0.508236961780607;
   fWeightMatrix0to1[4][0] = -1.40452870103845;
   fWeightMatrix0to1[5][0] = 0.0225680737660726;
   fWeightMatrix0to1[6][0] = 0.15042945056698;
   fWeightMatrix0to1[7][0] = -0.516722061235225;
   fWeightMatrix0to1[8][0] = -2.00954086679923;
   fWeightMatrix0to1[9][0] = 0.016813248397394;
   fWeightMatrix0to1[10][0] = -0.856413329815619;
   fWeightMatrix0to1[11][0] = -0.782852088654596;
   fWeightMatrix0to1[12][0] = -0.818871083733044;
   fWeightMatrix0to1[0][1] = 4.14793784329342;
   fWeightMatrix0to1[1][1] = -0.208676110114354;
   fWeightMatrix0to1[2][1] = 5.35152211006841;
   fWeightMatrix0to1[3][1] = 0.72532472753063;
   fWeightMatrix0to1[4][1] = 2.1070794622089;
   fWeightMatrix0to1[5][1] = 0.14718390856543;
   fWeightMatrix0to1[6][1] = 0.0527133841943663;
   fWeightMatrix0to1[7][1] = -2.18801936908403;
   fWeightMatrix0to1[8][1] = -9.83423306527679;
   fWeightMatrix0to1[9][1] = -1.56229388162746;
   fWeightMatrix0to1[10][1] = -5.83577090081939;
   fWeightMatrix0to1[11][1] = -1.41041970159734;
   fWeightMatrix0to1[12][1] = 0.26694944844235;
   fWeightMatrix0to1[0][2] = 0.705606579884049;
   fWeightMatrix0to1[1][2] = -0.345784389834996;
   fWeightMatrix0to1[2][2] = -10.6287880310544;
   fWeightMatrix0to1[3][2] = 1.00319421220283;
   fWeightMatrix0to1[4][2] = -0.17733024087835;
   fWeightMatrix0to1[5][2] = -0.271603672369194;
   fWeightMatrix0to1[6][2] = -0.183055280604947;
   fWeightMatrix0to1[7][2] = -0.384811449780481;
   fWeightMatrix0to1[8][2] = 1.38665554890003;
   fWeightMatrix0to1[9][2] = 0.0780280779916804;
   fWeightMatrix0to1[10][2] = 0.348269885501852;
   fWeightMatrix0to1[11][2] = 0.93148253790724;
   fWeightMatrix0to1[12][2] = -1.10747910672515;
   fWeightMatrix0to1[0][3] = 0.548519865736701;
   fWeightMatrix0to1[1][3] = -0.71954951980887;
   fWeightMatrix0to1[2][3] = 4.26729599036178;
   fWeightMatrix0to1[3][3] = 0.903214469713365;
   fWeightMatrix0to1[4][3] = -0.00144009484684223;
   fWeightMatrix0to1[5][3] = -0.96290436484822;
   fWeightMatrix0to1[6][3] = -7.87006490259645;
   fWeightMatrix0to1[7][3] = 0.41947807022903;
   fWeightMatrix0to1[8][3] = -3.87354876719256;
   fWeightMatrix0to1[9][3] = 0.644647034733012;
   fWeightMatrix0to1[10][3] = 2.00377631422164;
   fWeightMatrix0to1[11][3] = 1.05536333969375;
   fWeightMatrix0to1[12][3] = 0.718714098831014;
   fWeightMatrix0to1[0][4] = 1.84570583748069;
   fWeightMatrix0to1[1][4] = 0.0543383128949419;
   fWeightMatrix0to1[2][4] = -0.0829461282710167;
   fWeightMatrix0to1[3][4] = -1.51150117382515;
   fWeightMatrix0to1[4][4] = 0.150753667719207;
   fWeightMatrix0to1[5][4] = -6.66535853701947;
   fWeightMatrix0to1[6][4] = 0.00715895782133417;
   fWeightMatrix0to1[7][4] = 4.21197187082054;
   fWeightMatrix0to1[8][4] = 0.230371417320295;
   fWeightMatrix0to1[9][4] = 0.293635426612312;
   fWeightMatrix0to1[10][4] = 0.065195718673531;
   fWeightMatrix0to1[11][4] = -0.346969764252385;
   fWeightMatrix0to1[12][4] = 0.137479049966884;
   fWeightMatrix0to1[0][5] = -0.0347574177284942;
   fWeightMatrix0to1[1][5] = -0.53211208753902;
   fWeightMatrix0to1[2][5] = -0.100297783778599;
   fWeightMatrix0to1[3][5] = 1.86060129767306;
   fWeightMatrix0to1[4][5] = 0.427112832204132;
   fWeightMatrix0to1[5][5] = -0.086048902659789;
   fWeightMatrix0to1[6][5] = 0.0586027447469028;
   fWeightMatrix0to1[7][5] = 0.0764559321312855;
   fWeightMatrix0to1[8][5] = -0.0179872638006089;
   fWeightMatrix0to1[9][5] = 2.69918564163332;
   fWeightMatrix0to1[10][5] = -0.0664781525992779;
   fWeightMatrix0to1[11][5] = -2.52886251610623;
   fWeightMatrix0to1[12][5] = -2.43462113817948;
   fWeightMatrix0to1[0][6] = -1.01720119760192;
   fWeightMatrix0to1[1][6] = -0.783546098550409;
   fWeightMatrix0to1[2][6] = 0.486070185509292;
   fWeightMatrix0to1[3][6] = 0.187009061423717;
   fWeightMatrix0to1[4][6] = 1.29285912705321;
   fWeightMatrix0to1[5][6] = 1.77705228422215;
   fWeightMatrix0to1[6][6] = 0.138032346492732;
   fWeightMatrix0to1[7][6] = -0.953269262475227;
   fWeightMatrix0to1[8][6] = 0.906079575273394;
   fWeightMatrix0to1[9][6] = -0.551239215039664;
   fWeightMatrix0to1[10][6] = -6.56325991046924;
   fWeightMatrix0to1[11][6] = -3.43989166065869;
   fWeightMatrix0to1[12][6] = 1.16682767204109;
   fWeightMatrix0to1[0][7] = 1.2387779906139;
   fWeightMatrix0to1[1][7] = -0.948431818996249;
   fWeightMatrix0to1[2][7] = 3.74958790788948;
   fWeightMatrix0to1[3][7] = 0.231334993473118;
   fWeightMatrix0to1[4][7] = 0.713604093383696;
   fWeightMatrix0to1[5][7] = -0.632570675290422;
   fWeightMatrix0to1[6][7] = -17.5259299808296;
   fWeightMatrix0to1[7][7] = -1.47259743496499;
   fWeightMatrix0to1[8][7] = 4.1352232496409;
   fWeightMatrix0to1[9][7] = -2.21772237308445;
   fWeightMatrix0to1[10][7] = -0.316444238357516;
   fWeightMatrix0to1[11][7] = 0.531139748280983;
   fWeightMatrix0to1[12][7] = 1.53575367597895;
   fWeightMatrix0to1[0][8] = 3.7043875696968;
   fWeightMatrix0to1[1][8] = -0.252290077850076;
   fWeightMatrix0to1[2][8] = 5.80925386814115;
   fWeightMatrix0to1[3][8] = -0.498270258303866;
   fWeightMatrix0to1[4][8] = 0.560032229988722;
   fWeightMatrix0to1[5][8] = 4.31990507377074;
   fWeightMatrix0to1[6][8] = -25.5657072623898;
   fWeightMatrix0to1[7][8] = -4.15448939743956;
   fWeightMatrix0to1[8][8] = -9.84021665267574;
   fWeightMatrix0to1[9][8] = 0.00774925637406979;
   fWeightMatrix0to1[10][8] = -11.4853190599291;
   fWeightMatrix0to1[11][8] = 2.78979728534553;
   fWeightMatrix0to1[12][8] = 2.23684214404241;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.75816746994634;
   fWeightMatrix1to2[0][1] = 1.30162603337982;
   fWeightMatrix1to2[0][2] = -0.951445592136109;
   fWeightMatrix1to2[0][3] = -1.41438553902102;
   fWeightMatrix1to2[0][4] = -3.61160178327911;
   fWeightMatrix1to2[0][5] = -1.41109837908885;
   fWeightMatrix1to2[0][6] = 5.92583954587627;
   fWeightMatrix1to2[0][7] = 0.788868144792078;
   fWeightMatrix1to2[0][8] = 2.76324429701926;
   fWeightMatrix1to2[0][9] = 1.7320780748079;
   fWeightMatrix1to2[0][10] = 2.09948984164925;
   fWeightMatrix1to2[0][11] = -1.32912989931532;
   fWeightMatrix1to2[0][12] = -0.571469292400573;
   fWeightMatrix1to2[0][13] = 3.35962565516992;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.000170780578628;
   fMax_1[0][0] = 98.0028686523;
   fMin_1[1][0] = 0.0173324923962;
   fMax_1[1][0] = 99.7633666992;
   fMin_1[2][0] = 0.000170780578628;
   fMax_1[2][0] = 99.7633666992;
   fMin_1[0][1] = 5.68933501199e-05;
   fMax_1[0][1] = 1.02695572376;
   fMin_1[1][1] = 0.000123692952911;
   fMax_1[1][1] = 2.91128897667;
   fMin_1[2][1] = 5.68933501199e-05;
   fMax_1[2][1] = 2.91128897667;
   fMin_1[0][2] = 0.297363936901;
   fMax_1[0][2] = 22.4689235687;
   fMin_1[1][2] = 0.249220505357;
   fMax_1[1][2] = 15.8480386734;
   fMin_1[2][2] = 0.249220505357;
   fMax_1[2][2] = 22.4689235687;
   fMin_1[0][3] = 5.59860038757;
   fMax_1[0][3] = 1141.87963867;
   fMin_1[1][3] = 8.19970607758;
   fMax_1[1][3] = 1910.75646973;
   fMin_1[2][3] = 5.59860038757;
   fMax_1[2][3] = 1910.75646973;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 1;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 1;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 1;
   fMin_1[0][5] = 1.02196088392e-06;
   fMax_1[0][5] = 0.995764613152;
   fMin_1[1][5] = 4.12630924984e-06;
   fMax_1[1][5] = 0.981846272945;
   fMin_1[2][5] = 1.02196088392e-06;
   fMax_1[2][5] = 0.995764613152;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 44.1369857788;
   fMin_1[1][6] = 0.0150727918372;
   fMax_1[1][6] = 35.5466308594;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 44.1369857788;
   fMin_1[0][7] = 0.000102996826172;
   fMax_1[0][7] = 6.07498550415;
   fMin_1[1][7] = 0.00321638584137;
   fMax_1[1][7] = 5.60879898071;
   fMin_1[2][7] = 0.000102996826172;
   fMax_1[2][7] = 6.07498550415;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
