// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/05       [395781]
Creator        : bjoshi
Date           : Wed Jul 24 16:35:34 2019
Host           : Linux cmsbuild24.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/b/bjoshi/Analysis/workdirtmvaanalysisJul_11_2019/Code/CommonUtils/tmva
Training events: 39427
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
var_vertexKFChi2              var_vertexKFChi2              var_vertexKFChi2              Variable vertexKFChi2         units                             'F'    [0.000170780578628,99.855255127]
var_svpvTauAngle              var_svpvTauAngle              var_svpvTauAngle              Variable svpvTauAngle         units                             'F'    [5.68933501199e-05,1.49654066563]
var_flightLenSig              var_flightLenSig              var_flightLenSig              Variable flightLenSig         units                             'F'    [0.297363936901,23.564289093]
var_sumMuTrkKinkChi2          var_sumMuTrkKinkChi2          var_sumMuTrkKinkChi2          Variable sumMuTrkKinkChi2     units                             'F'    [5.59860038757,1974.1751709]
var_segCompMuMin              var_segCompMuMin              var_segCompMuMin              Variable segCompMuMin         units                             'F'    [0,1]
var_MinMIPLikelihood          var_MinMIPLikelihood          var_MinMIPLikelihood          Variable MinMIPLikelihood     units                             'F'    [7.14050031547e-07,0.995764613152]
var_isoMax                    var_isoMax                    var_isoMax                    Variable isoMax               units                             'F'    [0,44.1369857788]
var_maxdca                    var_maxdca                    var_maxdca                    Variable maxdca               units                             'F'    [0.000102996826172,6.07498550415]
NSpec 1
var_tauMass                   var_tauMass                   var_tauMass                   Variable tauMass              units                             'F'    [0.672131001949,3.83080458641]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var_vertexKFChi2", "var_svpvTauAngle", "var_flightLenSig", "var_sumMuTrkKinkChi2", "var_segCompMuMin", "var_MinMIPLikelihood", "var_isoMax", "var_maxdca" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[14][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][14];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.470304289408443;
   fWeightMatrix0to1[1][0] = 6.44648889526642;
   fWeightMatrix0to1[2][0] = -0.126701031623307;
   fWeightMatrix0to1[3][0] = -0.20001703396504;
   fWeightMatrix0to1[4][0] = -1.22736912379621;
   fWeightMatrix0to1[5][0] = 0.632504929825811;
   fWeightMatrix0to1[6][0] = -0.781000421663745;
   fWeightMatrix0to1[7][0] = 0.999456758385729;
   fWeightMatrix0to1[8][0] = -6.03791706753258;
   fWeightMatrix0to1[9][0] = 0.37061415829007;
   fWeightMatrix0to1[10][0] = -0.902493940445031;
   fWeightMatrix0to1[11][0] = -0.844491270598667;
   fWeightMatrix0to1[12][0] = -4.40468572791313;
   fWeightMatrix0to1[0][1] = 0.936283427170566;
   fWeightMatrix0to1[1][1] = -2.10421020588126;
   fWeightMatrix0to1[2][1] = 28.6997756520112;
   fWeightMatrix0to1[3][1] = 0.674830190163969;
   fWeightMatrix0to1[4][1] = 1.93428441204497;
   fWeightMatrix0to1[5][1] = 0.107548195819207;
   fWeightMatrix0to1[6][1] = 0.804450999723334;
   fWeightMatrix0to1[7][1] = -0.416720982978969;
   fWeightMatrix0to1[8][1] = -5.03297047493495;
   fWeightMatrix0to1[9][1] = 7.01515902708904;
   fWeightMatrix0to1[10][1] = -3.60692467765316;
   fWeightMatrix0to1[11][1] = -1.40692200517846;
   fWeightMatrix0to1[12][1] = -6.74519144890712;
   fWeightMatrix0to1[0][2] = 0.0276307627467492;
   fWeightMatrix0to1[1][2] = -0.937392832983843;
   fWeightMatrix0to1[2][2] = -0.761828940574826;
   fWeightMatrix0to1[3][2] = 0.192554270687295;
   fWeightMatrix0to1[4][2] = -0.826340514246199;
   fWeightMatrix0to1[5][2] = -0.579883022042969;
   fWeightMatrix0to1[6][2] = -1.89506898316413;
   fWeightMatrix0to1[7][2] = -2.50711282743381;
   fWeightMatrix0to1[8][2] = 1.45137909084078;
   fWeightMatrix0to1[9][2] = 4.42417920561237;
   fWeightMatrix0to1[10][2] = -0.722906466118338;
   fWeightMatrix0to1[11][2] = 1.16957148253809;
   fWeightMatrix0to1[12][2] = 0.735901793687018;
   fWeightMatrix0to1[0][3] = 2.1836383265211;
   fWeightMatrix0to1[1][3] = -0.988665893719046;
   fWeightMatrix0to1[2][3] = -0.878552628313913;
   fWeightMatrix0to1[3][3] = 2.86188184414612;
   fWeightMatrix0to1[4][3] = -0.566896984442057;
   fWeightMatrix0to1[5][3] = 0.832694791768166;
   fWeightMatrix0to1[6][3] = -2.15764082452625;
   fWeightMatrix0to1[7][3] = 2.58080161198695;
   fWeightMatrix0to1[8][3] = 1.69969218988983;
   fWeightMatrix0to1[9][3] = 5.61867314973316;
   fWeightMatrix0to1[10][3] = 4.09441732808713;
   fWeightMatrix0to1[11][3] = 0.968490193705825;
   fWeightMatrix0to1[12][3] = 0.681918175892625;
   fWeightMatrix0to1[0][4] = -5.49932561689285;
   fWeightMatrix0to1[1][4] = 0.0839051743988227;
   fWeightMatrix0to1[2][4] = -0.114300474864602;
   fWeightMatrix0to1[3][4] = 0.902142017738706;
   fWeightMatrix0to1[4][4] = -0.851451900641747;
   fWeightMatrix0to1[5][4] = -3.48607520688334;
   fWeightMatrix0to1[6][4] = -0.734527386720734;
   fWeightMatrix0to1[7][4] = -0.331670013955073;
   fWeightMatrix0to1[8][4] = -0.287234784885509;
   fWeightMatrix0to1[9][4] = 0.173167868462243;
   fWeightMatrix0to1[10][4] = -0.666272103568673;
   fWeightMatrix0to1[11][4] = 0.715236821962878;
   fWeightMatrix0to1[12][4] = 0.19232697249974;
   fWeightMatrix0to1[0][5] = -0.156647011632722;
   fWeightMatrix0to1[1][5] = -0.235958637264797;
   fWeightMatrix0to1[2][5] = -0.0378832774025501;
   fWeightMatrix0to1[3][5] = 1.8057401553216;
   fWeightMatrix0to1[4][5] = -0.733518389641601;
   fWeightMatrix0to1[5][5] = -2.69035000880784;
   fWeightMatrix0to1[6][5] = -1.21850752209894;
   fWeightMatrix0to1[7][5] = -0.00812534648678344;
   fWeightMatrix0to1[8][5] = -0.207462369740151;
   fWeightMatrix0to1[9][5] = 0.0861913801217025;
   fWeightMatrix0to1[10][5] = -0.199962453950494;
   fWeightMatrix0to1[11][5] = -1.47454405823532;
   fWeightMatrix0to1[12][5] = -0.0460222173682846;
   fWeightMatrix0to1[0][6] = 0.485626827777382;
   fWeightMatrix0to1[1][6] = -1.07770251761325;
   fWeightMatrix0to1[2][6] = -0.0283613099247975;
   fWeightMatrix0to1[3][6] = 0.694950154538925;
   fWeightMatrix0to1[4][6] = 0.88852750473098;
   fWeightMatrix0to1[5][6] = 0.934914053094184;
   fWeightMatrix0to1[6][6] = -1.27354607536117;
   fWeightMatrix0to1[7][6] = 0.792010782226853;
   fWeightMatrix0to1[8][6] = 2.95495982105092;
   fWeightMatrix0to1[9][6] = -0.273743516574387;
   fWeightMatrix0to1[10][6] = -0.13972224087359;
   fWeightMatrix0to1[11][6] = -2.53524782318045;
   fWeightMatrix0to1[12][6] = -6.91438863252347;
   fWeightMatrix0to1[0][7] = 0.115799400731975;
   fWeightMatrix0to1[1][7] = 0.89002205709973;
   fWeightMatrix0to1[2][7] = -11.1947053855966;
   fWeightMatrix0to1[3][7] = -1.8401500262881;
   fWeightMatrix0to1[4][7] = 1.37416987657689;
   fWeightMatrix0to1[5][7] = -1.69832457447381;
   fWeightMatrix0to1[6][7] = -1.47872269918207;
   fWeightMatrix0to1[7][7] = -0.552073067886199;
   fWeightMatrix0to1[8][7] = 1.94230409349463;
   fWeightMatrix0to1[9][7] = -7.07913106406528;
   fWeightMatrix0to1[10][7] = -1.41661497729647;
   fWeightMatrix0to1[11][7] = -0.0457064904026659;
   fWeightMatrix0to1[12][7] = 6.57695534953465;
   fWeightMatrix0to1[0][8] = -1.86049439905118;
   fWeightMatrix0to1[1][8] = 0.151871726545513;
   fWeightMatrix0to1[2][8] = 15.837458487307;
   fWeightMatrix0to1[3][8] = 0.132094342359023;
   fWeightMatrix0to1[4][8] = 0.50116096345871;
   fWeightMatrix0to1[5][8] = 2.34912761357564;
   fWeightMatrix0to1[6][8] = -1.82657716894791;
   fWeightMatrix0to1[7][8] = 1.41745726282998;
   fWeightMatrix0to1[8][8] = -3.84440180785061;
   fWeightMatrix0to1[9][8] = 8.05355152618315;
   fWeightMatrix0to1[10][8] = -0.696406343628894;
   fWeightMatrix0to1[11][8] = 2.5238830108439;
   fWeightMatrix0to1[12][8] = -9.66189761427916;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.837715266998112;
   fWeightMatrix1to2[0][1] = 0.759271113327588;
   fWeightMatrix1to2[0][2] = -2.9792842219947;
   fWeightMatrix1to2[0][3] = -0.434829840688726;
   fWeightMatrix1to2[0][4] = -1.3908599610696;
   fWeightMatrix1to2[0][5] = -0.56701167299156;
   fWeightMatrix1to2[0][6] = 3.382780070965;
   fWeightMatrix1to2[0][7] = -1.49558001742384;
   fWeightMatrix1to2[0][8] = 1.24755289183798;
   fWeightMatrix1to2[0][9] = -2.12196578330566;
   fWeightMatrix1to2[0][10] = -2.09332503910357;
   fWeightMatrix1to2[0][11] = -0.357464456144917;
   fWeightMatrix1to2[0][12] = 1.31836825028379;
   fWeightMatrix1to2[0][13] = 1.48157294004926;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.000170780578628;
   fMax_1[0][0] = 98.0028686523;
   fMin_1[1][0] = 0.0393699556589;
   fMax_1[1][0] = 99.855255127;
   fMin_1[2][0] = 0.000170780578628;
   fMax_1[2][0] = 99.855255127;
   fMin_1[0][1] = 5.68933501199e-05;
   fMax_1[0][1] = 1.02695572376;
   fMin_1[1][1] = 0.000263659138;
   fMax_1[1][1] = 1.49654066563;
   fMin_1[2][1] = 5.68933501199e-05;
   fMax_1[2][1] = 1.49654066563;
   fMin_1[0][2] = 0.297363936901;
   fMax_1[0][2] = 22.4689235687;
   fMin_1[1][2] = 0.400241583586;
   fMax_1[1][2] = 23.564289093;
   fMin_1[2][2] = 0.297363936901;
   fMax_1[2][2] = 23.564289093;
   fMin_1[0][3] = 5.59860038757;
   fMax_1[0][3] = 1141.87963867;
   fMin_1[1][3] = 6.3308172226;
   fMax_1[1][3] = 1974.1751709;
   fMin_1[2][3] = 5.59860038757;
   fMax_1[2][3] = 1974.1751709;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 1;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 1;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 1;
   fMin_1[0][5] = 1.02196088392e-06;
   fMax_1[0][5] = 0.995764613152;
   fMin_1[1][5] = 7.14050031547e-07;
   fMax_1[1][5] = 0.993460714817;
   fMin_1[2][5] = 7.14050031547e-07;
   fMax_1[2][5] = 0.995764613152;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 44.1369857788;
   fMin_1[1][6] = 0.0140209011734;
   fMax_1[1][6] = 36.4157524109;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 44.1369857788;
   fMin_1[0][7] = 0.000102996826172;
   fMax_1[0][7] = 6.07498550415;
   fMin_1[1][7] = 0.000502943992615;
   fMax_1[1][7] = 0.796667337418;
   fMin_1[2][7] = 0.000102996826172;
   fMax_1[2][7] = 6.07498550415;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
