// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/05       [395781]
Creator        : bjoshi
Date           : Wed Jul 24 13:58:18 2019
Host           : Linux cmsbuild24.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/b/bjoshi/Analysis/workdirtmvaanalysisJul_11_2019/Code/CommonUtils/tmva
Training events: 39279
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
var_vertexKFChi2              var_vertexKFChi2              var_vertexKFChi2              Variable vertexKFChi2         units                             'F'    [0.000170780578628,99.1781158447]
var_svpvTauAngle              var_svpvTauAngle              var_svpvTauAngle              Variable svpvTauAngle         units                             'F'    [5.68933501199e-05,2.77540850639]
var_flightLenSig              var_flightLenSig              var_flightLenSig              Variable flightLenSig         units                             'F'    [0.247926995158,22.4689235687]
var_sumMuTrkKinkChi2          var_sumMuTrkKinkChi2          var_sumMuTrkKinkChi2          Variable sumMuTrkKinkChi2     units                             'F'    [4.73337364197,2691.92041016]
var_segCompMuMin              var_segCompMuMin              var_segCompMuMin              Variable segCompMuMin         units                             'F'    [0,1]
var_MinMIPLikelihood          var_MinMIPLikelihood          var_MinMIPLikelihood          Variable MinMIPLikelihood     units                             'F'    [1.02196088392e-06,0.995764613152]
var_isoMax                    var_isoMax                    var_isoMax                    Variable isoMax               units                             'F'    [0,44.1369857788]
var_maxdca                    var_maxdca                    var_maxdca                    Variable maxdca               units                             'F'    [0.000102996826172,6.07498550415]
NSpec 1
var_tauMass                   var_tauMass                   var_tauMass                   Variable tauMass              units                             'F'    [0.672131001949,3.83080458641]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var_vertexKFChi2", "var_svpvTauAngle", "var_flightLenSig", "var_sumMuTrkKinkChi2", "var_segCompMuMin", "var_MinMIPLikelihood", "var_isoMax", "var_maxdca" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[14][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][14];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 1.05079124909045;
   fWeightMatrix0to1[1][0] = 5.62178991143357;
   fWeightMatrix0to1[2][0] = 2.1540438584949;
   fWeightMatrix0to1[3][0] = 0.90384502233288;
   fWeightMatrix0to1[4][0] = -1.22966555649601;
   fWeightMatrix0to1[5][0] = -1.86189915003138;
   fWeightMatrix0to1[6][0] = 1.1917610104733;
   fWeightMatrix0to1[7][0] = 0.79985515122641;
   fWeightMatrix0to1[8][0] = -0.786872861413173;
   fWeightMatrix0to1[9][0] = -1.37351247831012;
   fWeightMatrix0to1[10][0] = -0.696913354782842;
   fWeightMatrix0to1[11][0] = 1.84108412615956;
   fWeightMatrix0to1[12][0] = -1.99795154483444;
   fWeightMatrix0to1[0][1] = 1.75151784339329;
   fWeightMatrix0to1[1][1] = -1.61216771146029;
   fWeightMatrix0to1[2][1] = 10.5837080003878;
   fWeightMatrix0to1[3][1] = 0.278291403526284;
   fWeightMatrix0to1[4][1] = 1.69510083186591;
   fWeightMatrix0to1[5][1] = 0.479893593094732;
   fWeightMatrix0to1[6][1] = 0.487879667272356;
   fWeightMatrix0to1[7][1] = -3.8218663815026;
   fWeightMatrix0to1[8][1] = -20.0693492742763;
   fWeightMatrix0to1[9][1] = 4.22474348255534;
   fWeightMatrix0to1[10][1] = -5.48714681074405;
   fWeightMatrix0to1[11][1] = -3.06216851040946;
   fWeightMatrix0to1[12][1] = -1.62103532343199;
   fWeightMatrix0to1[0][2] = 1.37669571784949;
   fWeightMatrix0to1[1][2] = -0.208462236420665;
   fWeightMatrix0to1[2][2] = -9.92021058460291;
   fWeightMatrix0to1[3][2] = 0.37129291639992;
   fWeightMatrix0to1[4][2] = 0.38722290610548;
   fWeightMatrix0to1[5][2] = 1.62401285061509;
   fWeightMatrix0to1[6][2] = 0.242709409475173;
   fWeightMatrix0to1[7][2] = 0.132202593855257;
   fWeightMatrix0to1[8][2] = 0.843134501917225;
   fWeightMatrix0to1[9][2] = 1.24628835689281;
   fWeightMatrix0to1[10][2] = 0.183176422147674;
   fWeightMatrix0to1[11][2] = 0.265750578507283;
   fWeightMatrix0to1[12][2] = -1.96567567236394;
   fWeightMatrix0to1[0][3] = -1.03636940920106;
   fWeightMatrix0to1[1][3] = -1.04748127994988;
   fWeightMatrix0to1[2][3] = 4.36539171383257;
   fWeightMatrix0to1[3][3] = 2.53314742515703;
   fWeightMatrix0to1[4][3] = -0.408525754788448;
   fWeightMatrix0to1[5][3] = 0.283427121484147;
   fWeightMatrix0to1[6][3] = -3.03674610123006;
   fWeightMatrix0to1[7][3] = 0.100930998286773;
   fWeightMatrix0to1[8][3] = -0.393861801884182;
   fWeightMatrix0to1[9][3] = 5.52096003605063;
   fWeightMatrix0to1[10][3] = 3.51155275258406;
   fWeightMatrix0to1[11][3] = 6.00869613346733;
   fWeightMatrix0to1[12][3] = 1.70132023599538;
   fWeightMatrix0to1[0][4] = -2.19787193018007;
   fWeightMatrix0to1[1][4] = -0.0473466995804744;
   fWeightMatrix0to1[2][4] = -0.293969786509637;
   fWeightMatrix0to1[3][4] = -0.186013985909678;
   fWeightMatrix0to1[4][4] = -1.50085651363947;
   fWeightMatrix0to1[5][4] = -4.77858263785975;
   fWeightMatrix0to1[6][4] = -1.36545264144687;
   fWeightMatrix0to1[7][4] = 0.669501197018309;
   fWeightMatrix0to1[8][4] = 0.0793938387299381;
   fWeightMatrix0to1[9][4] = -0.037567248044945;
   fWeightMatrix0to1[10][4] = 0.0458583846064408;
   fWeightMatrix0to1[11][4] = -0.239590334080065;
   fWeightMatrix0to1[12][4] = 0.486762000724337;
   fWeightMatrix0to1[0][5] = -0.401684904716287;
   fWeightMatrix0to1[1][5] = 0.0444263571638631;
   fWeightMatrix0to1[2][5] = -0.013039405196236;
   fWeightMatrix0to1[3][5] = 0.931029571685539;
   fWeightMatrix0to1[4][5] = -0.39804090852342;
   fWeightMatrix0to1[5][5] = -0.543698818273767;
   fWeightMatrix0to1[6][5] = 0.0173510059504577;
   fWeightMatrix0to1[7][5] = 0.791874376645575;
   fWeightMatrix0to1[8][5] = -0.112311747598362;
   fWeightMatrix0to1[9][5] = -0.100538450773059;
   fWeightMatrix0to1[10][5] = 0.0186430165280359;
   fWeightMatrix0to1[11][5] = -0.321721542885316;
   fWeightMatrix0to1[12][5] = -1.17765935145544;
   fWeightMatrix0to1[0][6] = 1.60867665175985;
   fWeightMatrix0to1[1][6] = 0.363342253355614;
   fWeightMatrix0to1[2][6] = 0.175920997471409;
   fWeightMatrix0to1[3][6] = 0.889315643379008;
   fWeightMatrix0to1[4][6] = 1.50938325425161;
   fWeightMatrix0to1[5][6] = -0.642361564545679;
   fWeightMatrix0to1[6][6] = -1.12062335220837;
   fWeightMatrix0to1[7][6] = -0.197054903588567;
   fWeightMatrix0to1[8][6] = 0.190588057851289;
   fWeightMatrix0to1[9][6] = -0.0152659997419682;
   fWeightMatrix0to1[10][6] = -8.66508138919008;
   fWeightMatrix0to1[11][6] = -0.418968591879345;
   fWeightMatrix0to1[12][6] = 1.67162140869421;
   fWeightMatrix0to1[0][7] = -1.62098120431129;
   fWeightMatrix0to1[1][7] = -1.44066536428945;
   fWeightMatrix0to1[2][7] = 0.0185968613337749;
   fWeightMatrix0to1[3][7] = -0.196839469301583;
   fWeightMatrix0to1[4][7] = 1.61556070812374;
   fWeightMatrix0to1[5][7] = -1.57474729433999;
   fWeightMatrix0to1[6][7] = -4.64568929743181;
   fWeightMatrix0to1[7][7] = -2.26923697909437;
   fWeightMatrix0to1[8][7] = 0.713707396981945;
   fWeightMatrix0to1[9][7] = -1.9415655108511;
   fWeightMatrix0to1[10][7] = 0.0451446436669548;
   fWeightMatrix0to1[11][7] = 0.936489328501074;
   fWeightMatrix0to1[12][7] = 1.131226099984;
   fWeightMatrix0to1[0][8] = 1.26235905168143;
   fWeightMatrix0to1[1][8] = -0.579259763964142;
   fWeightMatrix0to1[2][8] = 8.40699449375365;
   fWeightMatrix0to1[3][8] = -1.38810424765309;
   fWeightMatrix0to1[4][8] = 0.241966360500387;
   fWeightMatrix0to1[5][8] = 2.34096659666169;
   fWeightMatrix0to1[6][8] = -5.98530424209551;
   fWeightMatrix0to1[7][8] = -5.30312813567663;
   fWeightMatrix0to1[8][8] = -20.0599525898035;
   fWeightMatrix0to1[9][8] = 8.19654089933253;
   fWeightMatrix0to1[10][8] = -11.6949666091315;
   fWeightMatrix0to1[11][8] = 5.47975715380141;
   fWeightMatrix0to1[12][8] = -1.14750259093133;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.594726170064825;
   fWeightMatrix1to2[0][1] = 1.40931952123535;
   fWeightMatrix1to2[0][2] = -0.710904087181037;
   fWeightMatrix1to2[0][3] = -4.52449280363291;
   fWeightMatrix1to2[0][4] = -2.91567198085417;
   fWeightMatrix1to2[0][5] = -0.740527556886046;
   fWeightMatrix1to2[0][6] = 1.29730232064926;
   fWeightMatrix1to2[0][7] = 0.34379013700082;
   fWeightMatrix1to2[0][8] = 6.29267046678069;
   fWeightMatrix1to2[0][9] = -2.16578209720407;
   fWeightMatrix1to2[0][10] = 3.0732146903782;
   fWeightMatrix1to2[0][11] = -3.28005433598753;
   fWeightMatrix1to2[0][12] = 0.653024274043661;
   fWeightMatrix1to2[0][13] = 3.2975661696422;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.000170780578628;
   fMax_1[0][0] = 98.0028686523;
   fMin_1[1][0] = 0.0213494841009;
   fMax_1[1][0] = 99.1781158447;
   fMin_1[2][0] = 0.000170780578628;
   fMax_1[2][0] = 99.1781158447;
   fMin_1[0][1] = 5.68933501199e-05;
   fMax_1[0][1] = 1.02695572376;
   fMin_1[1][1] = 0.000353074865416;
   fMax_1[1][1] = 2.77540850639;
   fMin_1[2][1] = 5.68933501199e-05;
   fMax_1[2][1] = 2.77540850639;
   fMin_1[0][2] = 0.297363936901;
   fMax_1[0][2] = 22.4689235687;
   fMin_1[1][2] = 0.247926995158;
   fMax_1[1][2] = 20.4737815857;
   fMin_1[2][2] = 0.247926995158;
   fMax_1[2][2] = 22.4689235687;
   fMin_1[0][3] = 5.59860038757;
   fMax_1[0][3] = 1141.87963867;
   fMin_1[1][3] = 4.73337364197;
   fMax_1[1][3] = 2691.92041016;
   fMin_1[2][3] = 4.73337364197;
   fMax_1[2][3] = 2691.92041016;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 1;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 1;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 1;
   fMin_1[0][5] = 1.02196088392e-06;
   fMax_1[0][5] = 0.995764613152;
   fMin_1[1][5] = 4.6827008191e-06;
   fMax_1[1][5] = 0.990950763226;
   fMin_1[2][5] = 1.02196088392e-06;
   fMax_1[2][5] = 0.995764613152;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 44.1369857788;
   fMin_1[1][6] = 0.0219718441367;
   fMax_1[1][6] = 30.3952789307;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 44.1369857788;
   fMin_1[0][7] = 0.000102996826172;
   fMax_1[0][7] = 6.07498550415;
   fMin_1[1][7] = 0.000661849975586;
   fMax_1[1][7] = 2.3642616272;
   fMin_1[2][7] = 0.000102996826172;
   fMax_1[2][7] = 6.07498550415;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
