// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/05       [395781]
Creator        : bjoshi
Date           : Wed Jul 24 14:08:47 2019
Host           : Linux cmsbuild24.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/b/bjoshi/Analysis/workdirtmvaanalysisJul_11_2019/Code/CommonUtils/tmva
Training events: 40716
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
var_vertexKFChi2              var_vertexKFChi2              var_vertexKFChi2              Variable vertexKFChi2         units                             'F'    [0.000170780578628,99.7748565674]
var_svpvTauAngle              var_svpvTauAngle              var_svpvTauAngle              Variable svpvTauAngle         units                             'F'    [5.68933501199e-05,2.79696989059]
var_flightLenSig              var_flightLenSig              var_flightLenSig              Variable flightLenSig         units                             'F'    [0.297363936901,22.4689235687]
var_sumMuTrkKinkChi2          var_sumMuTrkKinkChi2          var_sumMuTrkKinkChi2          Variable sumMuTrkKinkChi2     units                             'F'    [5.59860038757,3176.95581055]
var_segCompMuMin              var_segCompMuMin              var_segCompMuMin              Variable segCompMuMin         units                             'F'    [0,1]
var_MinMIPLikelihood          var_MinMIPLikelihood          var_MinMIPLikelihood          Variable MinMIPLikelihood     units                             'F'    [1.02196088392e-06,0.995764613152]
var_isoMax                    var_isoMax                    var_isoMax                    Variable isoMax               units                             'F'    [0,44.1369857788]
var_maxdca                    var_maxdca                    var_maxdca                    Variable maxdca               units                             'F'    [0.000102996826172,6.07498550415]
NSpec 1
var_tauMass                   var_tauMass                   var_tauMass                   Variable tauMass              units                             'F'    [0.672131001949,3.83080458641]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var_vertexKFChi2", "var_svpvTauAngle", "var_flightLenSig", "var_sumMuTrkKinkChi2", "var_segCompMuMin", "var_MinMIPLikelihood", "var_isoMax", "var_maxdca" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[14][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][14];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.485839557437028;
   fWeightMatrix0to1[1][0] = 6.54017948051502;
   fWeightMatrix0to1[2][0] = -0.193502651489522;
   fWeightMatrix0to1[3][0] = 0.15047234444457;
   fWeightMatrix0to1[4][0] = -0.79226227079834;
   fWeightMatrix0to1[5][0] = -0.534205333644812;
   fWeightMatrix0to1[6][0] = 0.133312853671795;
   fWeightMatrix0to1[7][0] = -3.8984585641318;
   fWeightMatrix0to1[8][0] = -1.2544320970834;
   fWeightMatrix0to1[9][0] = 1.19986846083877;
   fWeightMatrix0to1[10][0] = -0.0600742699940606;
   fWeightMatrix0to1[11][0] = -1.3401817871883;
   fWeightMatrix0to1[12][0] = -2.57384772350854;
   fWeightMatrix0to1[0][1] = 0.209229964417967;
   fWeightMatrix0to1[1][1] = -2.99276823898494;
   fWeightMatrix0to1[2][1] = 21.2869237711873;
   fWeightMatrix0to1[3][1] = -0.0029753223480462;
   fWeightMatrix0to1[4][1] = 2.35348767109117;
   fWeightMatrix0to1[5][1] = 0.36105766272001;
   fWeightMatrix0to1[6][1] = 2.20935813625281;
   fWeightMatrix0to1[7][1] = -4.09888445125447;
   fWeightMatrix0to1[8][1] = -20.776327921837;
   fWeightMatrix0to1[9][1] = 2.539692764015;
   fWeightMatrix0to1[10][1] = -7.93833044154429;
   fWeightMatrix0to1[11][1] = -1.45443995814673;
   fWeightMatrix0to1[12][1] = -1.70772056350167;
   fWeightMatrix0to1[0][2] = 0.000663000103676552;
   fWeightMatrix0to1[1][2] = -0.692947961534156;
   fWeightMatrix0to1[2][2] = -0.218428203462308;
   fWeightMatrix0to1[3][2] = 0.424295362304135;
   fWeightMatrix0to1[4][2] = 0.224427360581613;
   fWeightMatrix0to1[5][2] = 0.431328229255065;
   fWeightMatrix0to1[6][2] = 0.102338428443327;
   fWeightMatrix0to1[7][2] = -0.417419722407676;
   fWeightMatrix0to1[8][2] = 0.513046377212856;
   fWeightMatrix0to1[9][2] = -1.22835687086961;
   fWeightMatrix0to1[10][2] = -0.330362358136211;
   fWeightMatrix0to1[11][2] = 1.6707943998266;
   fWeightMatrix0to1[12][2] = -0.190091052325807;
   fWeightMatrix0to1[0][3] = 1.44710769401272;
   fWeightMatrix0to1[1][3] = -0.754534634262731;
   fWeightMatrix0to1[2][3] = -1.77939384133026;
   fWeightMatrix0to1[3][3] = 2.643906693878;
   fWeightMatrix0to1[4][3] = -0.230313780755246;
   fWeightMatrix0to1[5][3] = -0.283874186908083;
   fWeightMatrix0to1[6][3] = -11.1213462626644;
   fWeightMatrix0to1[7][3] = 0.370955835350973;
   fWeightMatrix0to1[8][3] = -3.65164545214485;
   fWeightMatrix0to1[9][3] = 4.24415736960286;
   fWeightMatrix0to1[10][3] = 0.915796530312547;
   fWeightMatrix0to1[11][3] = 2.37291268221007;
   fWeightMatrix0to1[12][3] = 0.415398021206788;
   fWeightMatrix0to1[0][4] = -3.09761626124449;
   fWeightMatrix0to1[1][4] = -0.0256214618535732;
   fWeightMatrix0to1[2][4] = 0.0443863406182469;
   fWeightMatrix0to1[3][4] = 1.07472401315512;
   fWeightMatrix0to1[4][4] = -2.88084232039236;
   fWeightMatrix0to1[5][4] = -5.74877756354252;
   fWeightMatrix0to1[6][4] = -0.48086303592268;
   fWeightMatrix0to1[7][4] = -0.335551734043879;
   fWeightMatrix0to1[8][4] = 0.275693989547943;
   fWeightMatrix0to1[9][4] = -0.527578818574111;
   fWeightMatrix0to1[10][4] = -0.0122240520836;
   fWeightMatrix0to1[11][4] = -0.630095200978396;
   fWeightMatrix0to1[12][4] = 0.589517528260044;
   fWeightMatrix0to1[0][5] = 0.0943434411098803;
   fWeightMatrix0to1[1][5] = 0.21336240456576;
   fWeightMatrix0to1[2][5] = 0.050493757853506;
   fWeightMatrix0to1[3][5] = 0.326717935901267;
   fWeightMatrix0to1[4][5] = -0.023225564258201;
   fWeightMatrix0to1[5][5] = 0.330829150868863;
   fWeightMatrix0to1[6][5] = -0.0422492805432827;
   fWeightMatrix0to1[7][5] = 0.538656024148514;
   fWeightMatrix0to1[8][5] = -0.0361628337875507;
   fWeightMatrix0to1[9][5] = -0.933867799606378;
   fWeightMatrix0to1[10][5] = -0.00317347561655954;
   fWeightMatrix0to1[11][5] = -3.3240929792066;
   fWeightMatrix0to1[12][5] = -0.821458412223877;
   fWeightMatrix0to1[0][6] = -0.29415481171647;
   fWeightMatrix0to1[1][6] = 0.397947055249627;
   fWeightMatrix0to1[2][6] = -0.249463264056927;
   fWeightMatrix0to1[3][6] = 1.11606457945227;
   fWeightMatrix0to1[4][6] = 0.36026179735388;
   fWeightMatrix0to1[5][6] = 0.700222476335539;
   fWeightMatrix0to1[6][6] = -0.421068888260622;
   fWeightMatrix0to1[7][6] = 0.724098466404277;
   fWeightMatrix0to1[8][6] = 0.114150226651437;
   fWeightMatrix0to1[9][6] = -0.906437752376571;
   fWeightMatrix0to1[10][6] = -8.44039385638983;
   fWeightMatrix0to1[11][6] = -0.346807468648029;
   fWeightMatrix0to1[12][6] = 0.335576945860692;
   fWeightMatrix0to1[0][7] = -1.16362662499409;
   fWeightMatrix0to1[1][7] = -0.48054566593289;
   fWeightMatrix0to1[2][7] = -1.17595332432554;
   fWeightMatrix0to1[3][7] = -0.647949699863392;
   fWeightMatrix0to1[4][7] = 1.9102271316832;
   fWeightMatrix0to1[5][7] = -2.02502924903439;
   fWeightMatrix0to1[6][7] = -3.08209466808459;
   fWeightMatrix0to1[7][7] = -0.22404067896115;
   fWeightMatrix0to1[8][7] = 0.135691288857872;
   fWeightMatrix0to1[9][7] = -1.0746201262303;
   fWeightMatrix0to1[10][7] = 0.634318321735247;
   fWeightMatrix0to1[11][7] = -0.193951558765561;
   fWeightMatrix0to1[12][7] = 1.41596941701309;
   fWeightMatrix0to1[0][8] = 0.358945646775688;
   fWeightMatrix0to1[1][8] = -0.51933984906225;
   fWeightMatrix0to1[2][8] = 18.4208871894007;
   fWeightMatrix0to1[3][8] = -0.243627188681273;
   fWeightMatrix0to1[4][8] = 0.671921022992264;
   fWeightMatrix0to1[5][8] = 3.20656455027522;
   fWeightMatrix0to1[6][8] = -11.7209908030472;
   fWeightMatrix0to1[7][8] = -7.1310502678641;
   fWeightMatrix0to1[8][8] = -25.4510044079775;
   fWeightMatrix0to1[9][8] = 4.90659068376403;
   fWeightMatrix0to1[10][8] = -15.5212492259104;
   fWeightMatrix0to1[11][8] = 4.49472947492328;
   fWeightMatrix0to1[12][8] = -1.60266474620812;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.994290748911003;
   fWeightMatrix1to2[0][1] = 1.09993345571956;
   fWeightMatrix1to2[0][2] = -5.3409872992482;
   fWeightMatrix1to2[0][3] = -5.85456857886845;
   fWeightMatrix1to2[0][4] = -2.11071484010488;
   fWeightMatrix1to2[0][5] = -0.832798343303859;
   fWeightMatrix1to2[0][6] = 3.00333608539137;
   fWeightMatrix1to2[0][7] = 1.37240987929525;
   fWeightMatrix1to2[0][8] = 4.72500494114946;
   fWeightMatrix1to2[0][9] = -0.622010497524613;
   fWeightMatrix1to2[0][10] = 2.34814046269811;
   fWeightMatrix1to2[0][11] = -0.894541186086934;
   fWeightMatrix1to2[0][12] = 0.245664178740928;
   fWeightMatrix1to2[0][13] = 4.28745900241566;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.000170780578628;
   fMax_1[0][0] = 98.0028686523;
   fMin_1[1][0] = 0.0347804948688;
   fMax_1[1][0] = 99.7748565674;
   fMin_1[2][0] = 0.000170780578628;
   fMax_1[2][0] = 99.7748565674;
   fMin_1[0][1] = 5.68933501199e-05;
   fMax_1[0][1] = 1.02695572376;
   fMin_1[1][1] = 0.00054168124916;
   fMax_1[1][1] = 2.79696989059;
   fMin_1[2][1] = 5.68933501199e-05;
   fMax_1[2][1] = 2.79696989059;
   fMin_1[0][2] = 0.297363936901;
   fMax_1[0][2] = 22.4689235687;
   fMin_1[1][2] = 0.376220405102;
   fMax_1[1][2] = 18.3871212006;
   fMin_1[2][2] = 0.297363936901;
   fMax_1[2][2] = 22.4689235687;
   fMin_1[0][3] = 5.59860038757;
   fMax_1[0][3] = 1141.87963867;
   fMin_1[1][3] = 7.15157079697;
   fMax_1[1][3] = 3176.95581055;
   fMin_1[2][3] = 5.59860038757;
   fMax_1[2][3] = 3176.95581055;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 1;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 1;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 1;
   fMin_1[0][5] = 1.02196088392e-06;
   fMax_1[0][5] = 0.995764613152;
   fMin_1[1][5] = 1.1731815448e-06;
   fMax_1[1][5] = 0.994231462479;
   fMin_1[2][5] = 1.02196088392e-06;
   fMax_1[2][5] = 0.995764613152;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 44.1369857788;
   fMin_1[1][6] = 0.0223290584981;
   fMax_1[1][6] = 39.0729026794;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 44.1369857788;
   fMin_1[0][7] = 0.000102996826172;
   fMax_1[0][7] = 6.07498550415;
   fMin_1[1][7] = 0.00090479850769;
   fMax_1[1][7] = 4.68758583069;
   fMin_1[2][7] = 0.000102996826172;
   fMax_1[2][7] = 6.07498550415;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
