// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/05       [395781]
Creator        : bjoshi
Date           : Thu Aug  1 08:43:56 2019
Host           : Linux cmsbuild24.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/b/bjoshi/Analysis/workdirtmvaanalysisJul_11_2019/Code/CommonUtils/tmva
Training events: 17566
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
var_vertexKFChi2              var_vertexKFChi2              var_vertexKFChi2              Variable vertexKFChi2         units                             'F'    [0.00230106944218,93.9320831299]
var_svpvTauAngle              var_svpvTauAngle              var_svpvTauAngle              Variable svpvTauAngle         units                             'F'    [5.54724174435e-05,1.49654066563]
var_flightLenSig              var_flightLenSig              var_flightLenSig              Variable flightLenSig         units                             'F'    [0.570846676826,40.3349914551]
var_sumMuTrkKinkChi2          var_sumMuTrkKinkChi2          var_sumMuTrkKinkChi2          Variable sumMuTrkKinkChi2     units                             'F'    [5.76008558273,1189.95141602]
var_segCompMuMin              var_segCompMuMin              var_segCompMuMin              Variable segCompMuMin         units                             'F'    [0,1]
var_MinMIPLikelihood          var_MinMIPLikelihood          var_MinMIPLikelihood          Variable MinMIPLikelihood     units                             'F'    [1.02196088392e-06,0.995328843594]
var_ntracks                   var_ntracks                   var_ntracks                   Variable ntracks              units                             'F'    [0,14]
var_relPt                     var_relPt                     var_relPt                     Variable relPt                units                             'F'    [0,7.89332342148]
var_isoMax                    var_isoMax                    var_isoMax                    Variable isoMax               units                             'F'    [0.0142688658088,40.4458084106]
var_maxdca                    var_maxdca                    var_maxdca                    Variable maxdca               units                             'F'    [0.000129699707031,2.14935803413]
var_tauMass                   var_tauMass                   var_tauMass                   Variable tauMass              units                             'F'    [0.841445505619,3.69498348236]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var_vertexKFChi2", "var_svpvTauAngle", "var_flightLenSig", "var_sumMuTrkKinkChi2", "var_segCompMuMin", "var_MinMIPLikelihood", "var_ntracks", "var_relPt", "var_isoMax", "var_maxdca", "var_tauMass" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.0502270829264403;
   fWeightMatrix0to1[1][0] = 2.30006402964863;
   fWeightMatrix0to1[2][0] = 0.374694615891769;
   fWeightMatrix0to1[3][0] = 1.66042597213277;
   fWeightMatrix0to1[4][0] = -2.76982712576731;
   fWeightMatrix0to1[5][0] = -1.5126021868677;
   fWeightMatrix0to1[6][0] = -0.899623421243753;
   fWeightMatrix0to1[7][0] = 2.44124648836923;
   fWeightMatrix0to1[8][0] = -2.75551812515969;
   fWeightMatrix0to1[9][0] = -1.38334961410628;
   fWeightMatrix0to1[10][0] = -3.29326968089498;
   fWeightMatrix0to1[11][0] = -0.204300944367776;
   fWeightMatrix0to1[12][0] = -0.477920184200342;
   fWeightMatrix0to1[13][0] = 0.372694638687561;
   fWeightMatrix0to1[14][0] = 0.59419001716174;
   fWeightMatrix0to1[15][0] = -0.0487315930106186;
   fWeightMatrix0to1[0][1] = 1.33662799819597;
   fWeightMatrix0to1[1][1] = 1.4757479611241;
   fWeightMatrix0to1[2][1] = -0.110585115860893;
   fWeightMatrix0to1[3][1] = 1.28363843091946;
   fWeightMatrix0to1[4][1] = -0.253250522407613;
   fWeightMatrix0to1[5][1] = -0.734209661238694;
   fWeightMatrix0to1[6][1] = 0.468340113648916;
   fWeightMatrix0to1[7][1] = -0.152396341212131;
   fWeightMatrix0to1[8][1] = -0.728102660091271;
   fWeightMatrix0to1[9][1] = -0.388385990224372;
   fWeightMatrix0to1[10][1] = -1.91241884142981;
   fWeightMatrix0to1[11][1] = 0.0458504809452044;
   fWeightMatrix0to1[12][1] = -2.03976476517011;
   fWeightMatrix0to1[13][1] = 1.94600869712628;
   fWeightMatrix0to1[14][1] = -1.01806284997085;
   fWeightMatrix0to1[15][1] = 4.07196822297619;
   fWeightMatrix0to1[0][2] = -0.651848990133794;
   fWeightMatrix0to1[1][2] = -0.317245607780285;
   fWeightMatrix0to1[2][2] = 0.0948630713178073;
   fWeightMatrix0to1[3][2] = -0.28977834588804;
   fWeightMatrix0to1[4][2] = -1.55347928372229;
   fWeightMatrix0to1[5][2] = 1.59765948783002;
   fWeightMatrix0to1[6][2] = -1.39567838116275;
   fWeightMatrix0to1[7][2] = 0.9078962391289;
   fWeightMatrix0to1[8][2] = 1.2010897556389;
   fWeightMatrix0to1[9][2] = 1.35025394422171;
   fWeightMatrix0to1[10][2] = 0.845070299735532;
   fWeightMatrix0to1[11][2] = 0.982238699706117;
   fWeightMatrix0to1[12][2] = -0.634829532413476;
   fWeightMatrix0to1[13][2] = -2.00454645644139;
   fWeightMatrix0to1[14][2] = 0.387104452040818;
   fWeightMatrix0to1[15][2] = 0.713706724645459;
   fWeightMatrix0to1[0][3] = 0.503823868656831;
   fWeightMatrix0to1[1][3] = 1.3818279904445;
   fWeightMatrix0to1[2][3] = 1.1768243996554;
   fWeightMatrix0to1[3][3] = 1.23680208947565;
   fWeightMatrix0to1[4][3] = -2.16778118703366;
   fWeightMatrix0to1[5][3] = 1.200217935568;
   fWeightMatrix0to1[6][3] = -1.67782375469029;
   fWeightMatrix0to1[7][3] = -1.19368414748608;
   fWeightMatrix0to1[8][3] = -0.507866368836016;
   fWeightMatrix0to1[9][3] = -2.58631572608561;
   fWeightMatrix0to1[10][3] = 1.24132706102386;
   fWeightMatrix0to1[11][3] = 1.0720330300848;
   fWeightMatrix0to1[12][3] = -1.76381810435506;
   fWeightMatrix0to1[13][3] = -0.596326259318017;
   fWeightMatrix0to1[14][3] = -0.818104512544896;
   fWeightMatrix0to1[15][3] = 3.2194718925621;
   fWeightMatrix0to1[0][4] = 0.277263926360249;
   fWeightMatrix0to1[1][4] = -0.0271649952359464;
   fWeightMatrix0to1[2][4] = -0.77804288447064;
   fWeightMatrix0to1[3][4] = -1.15928613227496;
   fWeightMatrix0to1[4][4] = 0.054730096672246;
   fWeightMatrix0to1[5][4] = -0.850232497815419;
   fWeightMatrix0to1[6][4] = -0.61117754952833;
   fWeightMatrix0to1[7][4] = -1.02911725150736;
   fWeightMatrix0to1[8][4] = -0.702304585947433;
   fWeightMatrix0to1[9][4] = 1.06242379581561;
   fWeightMatrix0to1[10][4] = -0.269296277272437;
   fWeightMatrix0to1[11][4] = -1.08414999858801;
   fWeightMatrix0to1[12][4] = -1.55220491728575;
   fWeightMatrix0to1[13][4] = 0.197951451980816;
   fWeightMatrix0to1[14][4] = 3.07337002279916;
   fWeightMatrix0to1[15][4] = -0.0532634848282559;
   fWeightMatrix0to1[0][5] = 0.254496769783281;
   fWeightMatrix0to1[1][5] = 0.787988561304256;
   fWeightMatrix0to1[2][5] = 0.928027237879984;
   fWeightMatrix0to1[3][5] = -0.948969004986185;
   fWeightMatrix0to1[4][5] = -0.70136685527298;
   fWeightMatrix0to1[5][5] = -0.547426634354528;
   fWeightMatrix0to1[6][5] = 0.918240000924212;
   fWeightMatrix0to1[7][5] = -1.07107632662932;
   fWeightMatrix0to1[8][5] = -0.695223671614106;
   fWeightMatrix0to1[9][5] = -1.7827829507177;
   fWeightMatrix0to1[10][5] = 0.292852813493666;
   fWeightMatrix0to1[11][5] = 0.192190143748148;
   fWeightMatrix0to1[12][5] = 1.70391302086403;
   fWeightMatrix0to1[13][5] = -0.0819298345093805;
   fWeightMatrix0to1[14][5] = -0.493826877967938;
   fWeightMatrix0to1[15][5] = 0.0607578962577938;
   fWeightMatrix0to1[0][6] = -0.804717709416703;
   fWeightMatrix0to1[1][6] = -1.71567199985633;
   fWeightMatrix0to1[2][6] = -1.51650124953815;
   fWeightMatrix0to1[3][6] = 0.140570883036821;
   fWeightMatrix0to1[4][6] = -1.66845945438465;
   fWeightMatrix0to1[5][6] = -1.94716387013203;
   fWeightMatrix0to1[6][6] = 0.435423852702919;
   fWeightMatrix0to1[7][6] = 1.41622216014386;
   fWeightMatrix0to1[8][6] = -1.43892211052397;
   fWeightMatrix0to1[9][6] = 1.06544607336241;
   fWeightMatrix0to1[10][6] = -0.60813991772152;
   fWeightMatrix0to1[11][6] = -0.671290478905774;
   fWeightMatrix0to1[12][6] = 0.0251603097927367;
   fWeightMatrix0to1[13][6] = 0.450751599431613;
   fWeightMatrix0to1[14][6] = -1.70720433553599;
   fWeightMatrix0to1[15][6] = -0.0353771586730822;
   fWeightMatrix0to1[0][7] = 0.459628337766528;
   fWeightMatrix0to1[1][7] = 0.269225583416585;
   fWeightMatrix0to1[2][7] = -1.56400255795633;
   fWeightMatrix0to1[3][7] = 1.90115441679477;
   fWeightMatrix0to1[4][7] = 0.0786198316640158;
   fWeightMatrix0to1[5][7] = -1.1749208975354;
   fWeightMatrix0to1[6][7] = 0.525141913514473;
   fWeightMatrix0to1[7][7] = -1.3594988714129;
   fWeightMatrix0to1[8][7] = -2.34092187321421;
   fWeightMatrix0to1[9][7] = -0.0303107049467246;
   fWeightMatrix0to1[10][7] = 0.138094612406115;
   fWeightMatrix0to1[11][7] = 1.7467105976687;
   fWeightMatrix0to1[12][7] = 0.906090638238332;
   fWeightMatrix0to1[13][7] = -0.299354455546374;
   fWeightMatrix0to1[14][7] = -0.650710414171374;
   fWeightMatrix0to1[15][7] = 0.460932127684738;
   fWeightMatrix0to1[0][8] = -2.76749614878196;
   fWeightMatrix0to1[1][8] = 0.919102752404234;
   fWeightMatrix0to1[2][8] = -0.110443178084219;
   fWeightMatrix0to1[3][8] = -1.95371183574276;
   fWeightMatrix0to1[4][8] = 0.22723482297716;
   fWeightMatrix0to1[5][8] = -1.38559340585263;
   fWeightMatrix0to1[6][8] = -0.182059662782142;
   fWeightMatrix0to1[7][8] = 0.917037837067825;
   fWeightMatrix0to1[8][8] = 1.9030755427192;
   fWeightMatrix0to1[9][8] = -1.29641637918365;
   fWeightMatrix0to1[10][8] = 0.0828432302435319;
   fWeightMatrix0to1[11][8] = 0.589566015163845;
   fWeightMatrix0to1[12][8] = 1.80003166248709;
   fWeightMatrix0to1[13][8] = -0.133648361992728;
   fWeightMatrix0to1[14][8] = -0.757414685784728;
   fWeightMatrix0to1[15][8] = -0.159067047998525;
   fWeightMatrix0to1[0][9] = -1.49703248592864;
   fWeightMatrix0to1[1][9] = 1.43854473776497;
   fWeightMatrix0to1[2][9] = 0.8024508390565;
   fWeightMatrix0to1[3][9] = -0.589615029772181;
   fWeightMatrix0to1[4][9] = -0.955538651058903;
   fWeightMatrix0to1[5][9] = 0.0207343858108093;
   fWeightMatrix0to1[6][9] = -1.59976557246065;
   fWeightMatrix0to1[7][9] = 0.408850347457397;
   fWeightMatrix0to1[8][9] = 1.73014611663869;
   fWeightMatrix0to1[9][9] = -0.881616597515987;
   fWeightMatrix0to1[10][9] = -0.985775294972256;
   fWeightMatrix0to1[11][9] = -0.263653777543112;
   fWeightMatrix0to1[12][9] = 1.16362003586825;
   fWeightMatrix0to1[13][9] = -0.911936544296848;
   fWeightMatrix0to1[14][9] = 0.615819429151492;
   fWeightMatrix0to1[15][9] = 0.594883237386888;
   fWeightMatrix0to1[0][10] = 9.8357586046048;
   fWeightMatrix0to1[1][10] = 0.647435390438715;
   fWeightMatrix0to1[2][10] = 2.58161509102268;
   fWeightMatrix0to1[3][10] = 0.560335705809848;
   fWeightMatrix0to1[4][10] = 0.941294974705335;
   fWeightMatrix0to1[5][10] = -0.642418722238237;
   fWeightMatrix0to1[6][10] = -0.702566841981439;
   fWeightMatrix0to1[7][10] = 1.0307684290367;
   fWeightMatrix0to1[8][10] = -0.0799614158390003;
   fWeightMatrix0to1[9][10] = -0.632118326713681;
   fWeightMatrix0to1[10][10] = 15.4104809576404;
   fWeightMatrix0to1[11][10] = 1.44662615536962;
   fWeightMatrix0to1[12][10] = 0.150979341153465;
   fWeightMatrix0to1[13][10] = 5.07573105792944;
   fWeightMatrix0to1[14][10] = 4.52463867577572;
   fWeightMatrix0to1[15][10] = -27.908796378015;
   fWeightMatrix0to1[0][11] = -0.225917362046032;
   fWeightMatrix0to1[1][11] = 0.177010027657919;
   fWeightMatrix0to1[2][11] = 0.88669956233426;
   fWeightMatrix0to1[3][11] = -1.59862794237353;
   fWeightMatrix0to1[4][11] = -1.0782765922803;
   fWeightMatrix0to1[5][11] = 1.25096949774685;
   fWeightMatrix0to1[6][11] = 2.07053448839519;
   fWeightMatrix0to1[7][11] = -1.45108093343172;
   fWeightMatrix0to1[8][11] = 0.0158888594617286;
   fWeightMatrix0to1[9][11] = -0.664165649551791;
   fWeightMatrix0to1[10][11] = 0.781084426406911;
   fWeightMatrix0to1[11][11] = 2.18929577592871;
   fWeightMatrix0to1[12][11] = -0.534797940426457;
   fWeightMatrix0to1[13][11] = 1.26381839834519;
   fWeightMatrix0to1[14][11] = -1.13218572081783;
   fWeightMatrix0to1[15][11] = -1.35113339504166;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 2.90257101174921;
   fWeightMatrix1to2[0][1] = 0.555805330559521;
   fWeightMatrix1to2[0][2] = -0.878543012650148;
   fWeightMatrix1to2[0][3] = -2.29964509771964;
   fWeightMatrix1to2[0][4] = -1.36783740135232;
   fWeightMatrix1to2[0][5] = 2.35579042370881;
   fWeightMatrix1to2[0][6] = 1.48520772724697;
   fWeightMatrix1to2[0][7] = -2.79083150264576;
   fWeightMatrix1to2[0][8] = -1.34993586140697;
   fWeightMatrix1to2[0][9] = 1.73868144657387;
   fWeightMatrix1to2[0][10] = 3.32667120092016;
   fWeightMatrix1to2[0][11] = -3.39410576257985;
   fWeightMatrix1to2[0][12] = 0.32307475632581;
   fWeightMatrix1to2[0][13] = -3.63868279045667;
   fWeightMatrix1to2[0][14] = 0.455594012074823;
   fWeightMatrix1to2[0][15] = -10.0959459391258;
   fWeightMatrix1to2[0][16] = 3.00657715763115;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.00230106944218;
   fMax_1[0][0] = 93.9320831299;
   fMin_1[1][0] = 0.0381665080786;
   fMax_1[1][0] = 91.3706054688;
   fMin_1[2][0] = 0.00230106944218;
   fMax_1[2][0] = 93.9320831299;
   fMin_1[0][1] = 5.54724174435e-05;
   fMax_1[0][1] = 1.02695572376;
   fMin_1[1][1] = 0.000263659138;
   fMax_1[1][1] = 1.49654066563;
   fMin_1[2][1] = 5.54724174435e-05;
   fMax_1[2][1] = 1.49654066563;
   fMin_1[0][2] = 0.782265663147;
   fMax_1[0][2] = 21.753194809;
   fMin_1[1][2] = 0.570846676826;
   fMax_1[1][2] = 40.3349914551;
   fMin_1[2][2] = 0.570846676826;
   fMax_1[2][2] = 40.3349914551;
   fMin_1[0][3] = 5.76008558273;
   fMax_1[0][3] = 1026.62243652;
   fMin_1[1][3] = 8.05385398865;
   fMax_1[1][3] = 1189.95141602;
   fMin_1[2][3] = 5.76008558273;
   fMax_1[2][3] = 1189.95141602;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 1;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 1;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 1;
   fMin_1[0][5] = 1.02196088392e-06;
   fMax_1[0][5] = 0.995328843594;
   fMin_1[1][5] = 2.44330976784e-06;
   fMax_1[1][5] = 0.993460714817;
   fMin_1[2][5] = 1.02196088392e-06;
   fMax_1[2][5] = 0.995328843594;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 11;
   fMin_1[1][6] = 0;
   fMax_1[1][6] = 14;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 14;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 4.82540559769;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 7.89332342148;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 7.89332342148;
   fMin_1[0][8] = 0.0142688658088;
   fMax_1[0][8] = 40.4458084106;
   fMin_1[1][8] = 0.0299532283098;
   fMax_1[1][8] = 38.8205451965;
   fMin_1[2][8] = 0.0142688658088;
   fMax_1[2][8] = 40.4458084106;
   fMin_1[0][9] = 0.000129699707031;
   fMax_1[0][9] = 0.977394580841;
   fMin_1[1][9] = 0.000481247901917;
   fMax_1[1][9] = 2.14935803413;
   fMin_1[2][9] = 0.000129699707031;
   fMax_1[2][9] = 2.14935803413;
   fMin_1[0][10] = 0.841445505619;
   fMax_1[0][10] = 3.69498348236;
   fMin_1[1][10] = 1.60006630421;
   fMax_1[1][10] = 1.73087322712;
   fMin_1[2][10] = 0.841445505619;
   fMax_1[2][10] = 3.69498348236;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
